### ISSUE TITLE
Smart compile of edited code

### ISSUE THREAD

**Issue by Nuklon** [0xd4d/dnSpy#755]
Thanks for this wonderful application @0xd4d, it's by far the best 👍 

There's one issue I'm having with it though. When a method/property is edited, dnSpy tries to compile too much (I think the entire application is recompiled?). This works OK for very simple applications but almost all larger applications fail (and very often the obfuscated ones). For simple changes (like _return true_ or _return ""_) it could try to compile just that to IL instead. Now I'd have to write everything in IL, which is OK but not as convenient as it could be.

**Comment by UlyssesWu** [comment]
> I think the entire application is recompiled?

Sounds like a joke.

> For simple changes (like return true or return "") 

![dnspy](https://user-images.githubusercontent.com/4312781/36935114-25ed96ec-1f2e-11e8-9fff-c38770667ceb.png)

**Comment by Nuklon** [comment]
Yes, that exists, but is too limited and doesn't update the class like the other functions.

**Comment by 0xd4d** [comment]
First of all, make sure you're using the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts).

Do you edit the whole class at the same time? It's recommended to only edit one method at a time, i.e., choose "Edit Method (C#)" and not "Edit Class (C#)", that will result in less problems.

Note that the hex commands seen in the picture above use the hex editor, so you'd have to save the file and then reload it to see any changes. It's good if you only have simple changes to make and want to modify as few bytes as possible. The IL editor and C# code editor rewrite the whole assembly when you save it.

**Comment by Nuklon** [comment]
If I'm using the latest build the edit throws an exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.IsPublicKeyToken(PublicKeyToken[] tokens, PublicKeyToken token)
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.<GetResolvedContractAssemblies>d__13.MoveNext()
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.<GetAssemblies>d__9.MoveNext()
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.<GetAssemblies>d__7.MoveNext()
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.Initialize(IEnumerable`1 extraAssemblyReferences)
   at dnSpy.AsmEditor.Compiler.MetadataReferenceFinder.<Find>d__5.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at dnSpy.AsmEditor.Compiler.EditCodeVM.CreateCompilerMetadataReferencesAsync(IEnumerable`1 extraAssemblyReferences, CancellationToken cancellationToken)
   at dnSpy.AsmEditor.Compiler.EditCodeVM.<DecompileAndGetRefsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnSpy.AsmEditor.Compiler.EditCodeVM.<StartDecompileAsync>d__78.MoveNext()

If I use some older version of dnSpy (this one for example: https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.657/artifacts) it's all errors like this:
https://i.imgur.com/Kh0dDib.png

The class and code is valid. I'll try which version starts throwing the exception in the editor, will update here later.

**Comment by 0xd4d** [comment]
Could you attach the files here, if it's a Unity game, zip the whole Managed folder. Also write down which method you're trying to edit.

**Comment by Nuklon** [comment]
Yes, now that's working indeed, thank you for the quick fix 👍 

Compiling is still not working though (same errors as in the screenshot I've posted above).
If I manually edit a method's IL it's working, but it's not very convenient.

I was more thinking in terms of some very basic feature to compile a body to IL. I'm not really sure how to word it, but hope you understand what I mean.

**Comment by Nuklon** [comment]
[tryme.txt](https://github.com/0xd4d/dnSpy/files/1777609/tryme.txt)
In case you want to give it a try, just edit any method and it won't compile (for example, GiroNe.Cryptor.Decrypt). It's obfuscated, but IL editing works OK. 
For some more complicated methods I create a separate console app and copy IL parts from it, which is not ideal.

While uploading this I also received a dialog from dnSpy with an exception:
https://i.imgur.com/naFScN6.png

**Comment by 0xd4d** [comment]
Fixed.

Your file explains why you can't edit it, it's obfuscated. Use de4dot first since the compiler doesn't allow any type of character in identifiers.

**Comment by Nuklon** [comment]
Yes, I expected as much, which is why I was thinking that something like a 'lite' version of compiling would be great. Which could just compile the lines I'm editing (and can then be translated to IL). 

This also happens with some other, non-obfuscated, executables. I don't have an example at the moment but if something can't compile in the entire executable you still can't edit _just the method_.

**Comment by 0xd4d** [comment]
This is a dupe of #165

A workaround is to create a new class, add your code in it, then open the IL editor and copy whatever you added and paste it in the real method you want to edit.
